### ISSUE TITLE
[BUG] - Edição de agendamento

### ISSUE THREAD

**Issue by AlvaroLeles** [fga-eps-mds/2023-1-Schedula-Doc#101]
## Descrição
Ao tentar atualizar um agendamento, um erro é disparado avisando que ocorreu um problema. Além disso, o visual superior do popup de edição parece estranho.

## Como reproduzir:
Tentar editar um agendamento e clicar em "Atualizar agendamento"

## Comportamento esperado:
Era esperado que a edição fosse concluída, os dados alterados, e essas alterações refletidas em tela.

## Screenshots:
![image](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/assets/54085562/1c016f22-1bd6-4495-b326-380a2f6840da)

**Comment by guilhermemoraisr** [comment]
## 📑 Test Plan

**Atenção:** é necessário que o microservice de Detalhamento de Chamados esteja com o código atualizado da branch [#101](https://github.com/fga-eps-mds/2023-1-schedula-detalhador-de-chamados/tree/%23101-edicao_de_agendamento). Caso ela não exista, é porque o PR ao qual ela está ligada já foi aceito, e seu código está na develop.

1. Faça o login no Schedula.
2. Na aba "Agendamentos", verifique se os agendamentos que possuem status de "Em Andamento" estão na cor verde, conforme imagem abaixo:
![image](https://github.com/fga-eps-mds/2023-1-schedula-front/assets/48729770/6b41972c-a8a9-455b-bdfe-d8a4f4e7c0ef)
3. Logado com usuário de nível admin, clique no ícone de edição e tente editar todos os campos possíveis: edite a data e hora do evento (é preciso ser uma data futura); exclua os agendamentos e coloque alguma data futura, mas que seja antes da data e hora do agendamento; edite a descrição; altere o status.
![image](https://github.com/fga-eps-mds/2023-1-schedula-front/assets/48729770/f8a9d04a-59f0-4b5d-9977-de553df7c947)
4. Verifique se os dados editados foram atualizados com sucesso.
![image](https://github.com/fga-eps-mds/2023-1-schedula-front/assets/48729770/f13559fa-f8c2-4e2b-a054-9da8d6cd0afd)
