### ISSUE TITLE
Limitar descrição de chamado a 500 caracteres

### ISSUE THREAD

**Issue by AlvaroLeles** [fga-eps-mds/2023-1-Schedula-Doc#104]

**Comment by italovinicius18** [comment]
@AlvaroLeles poderia descrever melhor em qual local seria a inserção dessa descrição.

Não seria a descrição do agendamento?

**Comment by AlvaroLeles** [comment]
É para certificar que a propriedade "Descrição" de um agendamento não passe de 500 caracteres.
