### ISSUE TITLE
[US01] - Gerenciamento de categorias de tutorial

### ISSUE THREAD

**Issue by AlvaroLeles** [fga-eps-mds/2023-1-Schedula-Doc#25]
### Descrição:

Eu como administrador desejo gerenciar categorias de tutorial para que eu possa organizar e buscar tutoriais de maneira otimizada.

### Tarefas:

- [x] Possuir tela de categoria;
- [x] Listar as categorias;
- [x] Botão para adicionar uma nova categoria;
- [x] Formulário para nova categoria;
- [x] Botão para editar categoria;
- [x] Botão para remover categoria;

### Critérios de aceitação:

- Não deve permitir que haja duplicidade de categoria;
- Garantir acesso apenas de usuários administradores;
- Garantir que não seja adicionado categorias sem texto;
- Garantir limite do texto com um máximo de 50 caracteres;
- Somente caracteres de texto no campo da categoria;
- Só permitir exclusão da categoria se não tiver nenhuma categoria associada.

### Observações

Escopo relacionado apenas ao crud das categorias do tutorial e não ao crud dos tutoriais

**Comment by gabrielbpn** [comment]
![image](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/assets/58351486/67686c46-08c0-47e2-9126-10f4bc35718b)
