### ISSUE TITLE
[US02] - Exportar dados de postos de trabalho via API

### ISSUE THREAD

**Issue by AlvaroLeles** [fga-eps-mds/2023-1-Schedula-Doc#26]
### Tarefas:

- [ ] Tarefa 1;
- [ ] Tarefa 2;
- [ ] Tarefa 3;

### Critérios de aceitação:

- Paulo vinícius deverá conseguir ;
- Paulo vinícius não deverá conseguir ;
- CI estar passando ;
- Respeitar todas as orientações acima.

### Tela (caso não tenha, delete essa parte)

- A issue deve ser pontuada;
- A issue deve ser delegada a alguém;
- A issue deve ter labels;

**Comment by gabrielbpn** [comment]
![image](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/assets/58351486/e0732dd9-fd0c-4a1b-bf83-60678f883f35)
