### ISSUE TITLE
[US04] - Página de acesso a tutoriais

### ISSUE THREAD

**Issue by AlvaroLeles** [fga-eps-mds/2023-1-Schedula-Doc#27]
### Descrição:

Eu como usuário interno desejo acessar tutoriais específicos para ajudar a resolver e tirar dúvidas sobre um problema de infraestrutura.

### Tarefas:

- [x] Possuir barra de pesquisa;
- [x] Listar tutorias;
- [x] Realizar download do tutorial selecionado;
- [x] Mostrar títulos dos tutoriais;
- [x] Agrupar tutorias pelas categorias;
- [ ] Ordenar tutoriais por ordem alfabética;

### Critérios de aceitação:

- Acesso ao documento selecionado.
- Listar tutoriais baseando-se nos filtros.
- Acesso apenas para usuários logados.
- Respeitar todas as orientações acima.
- Baixar ao clicar no card todo, não somente no botão de download

### Protótipo da tela [FIGMA](https://www.figma.com/proto/Zn3jP0CN3ANk2Aruz3Vegg/Acessar-tutoriais?type=design&node-id=9-10&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=9%3A10) (VALIDADO)

- A issue deve ser pontuada;
- A issue deve ser delegada a alguém;
- A issue deve ter labels;

**Comment by guilhermemoraisr** [comment]
O Pupak solicitou que para disparar o download de um tutorial, ele possa clicar em qualquer região desse card, e não apenas onde está escrito download. Ou seja o botão de download seria o card inteiro:
![image.png](https://images.zenhubusercontent.com/6231307dc8b92a2517b9a208/a9b5c5c7-ee5b-42b1-8191-9d74f3701fbe)

**Comment by gabrielbpn** [comment]
![image](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/assets/58351486/537c2974-755b-4969-be62-81040f8a85f5)
