### ISSUE TITLE
[US05] - Gerenciamento de tutoriais

### ISSUE THREAD

**Issue by AlvaroLeles** [fga-eps-mds/2023-1-Schedula-Doc#28]
### Descrição: 
Eu como administrador desejo gerenciar tutoriais.

### Tarefas:

- [x] Possuir tela de cadastro de tutorial;
- [x] Possuir tela de editar um tutorial;
- [x] Botão para criação do tutorial;
- [x] Campo para preenchimento de nome do tutorial;
- [x] Campo para selecionar a categoria do tutorial;
- [x] Campo para adicionar PDF; 
- [x] Botão para excluir tutorial;
- [x] Botão para editar tutorial;

### Critérios de aceitação:

- Acesso à criação e remoção de tutoriais somente pelo administrador;
- Não permitir o cadastro de tutoriais iguais;
- Excluir mais de um tutorial por vez;
- Obrigatório nome no tutorial;
- Limitar a quantidade de caracteres do nome (500);
- Tutoriais precisam estar vinculados a uma categoria.
- Poder editar os tutorias criados. 

### Tela [FIGMA](https://www.figma.com/file/e1d9VEVrL7jw8P6xlmuXHZ/Prot%C3%B3tipo-Schedula---US05---Gerenciamento-de-Tutoriais?type=design&node-id=0%3A1&t=9jM51HS3aGr7s2iK-1)

- A issue deve ser pontuada;
- A issue deve ser delegada a alguém;
- A issue deve ter labels;

**Comment by AlvaroLeles** [comment]
Formato popup
Botão de excluir selecionados
Botão para selecionar todos

**Comment by gabrielbpn** [comment]
![image](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/assets/58351486/5edcce98-bebf-4dd9-bcb9-0f4eef62f425)
