### ISSUE TITLE
[US06] - Disponibilizar chamados abertos para usuário externo

### ISSUE THREAD

**Issue by AlvaroLeles** [fga-eps-mds/2023-1-Schedula-Doc#30]
### Tarefas:

- [x] Possuir tela de agendamentos abertos;
- [x] Botão localizado na tela de login para levar à tela de agendamentos abertos;
- [ ] Possuir categoria, local, solicitante, telefone, data, hora, tipo, atendente, status para cada agendamento;
- [x] Possuir card para cada agendamento aberto;
- [x] Possuir botão de criação de agendamento para usuário externo.

### Critérios de aceitação:

- Qualquer usuário pode ver o botão de "agendamentos abertos" na tela de login;
- Qualquer usuário pode acessar a página de agendamentos abertos;
- A página de agendamentos deve listar todos os agendamentos abertos;
- A página de agendamentos não deve listar qualquer agendamento que não esteja aberto (ex: homologação ou fechado);
- Os dados do agendamento devem ser exatamente os registrados no banco;
- O botão de novo agendamento deve levar à página de criação de agendamentos por usuário externo;
- O identificador de usuário deve ser mostrado como usuário externo e, quando clicado, deve voltar à pagina de login;
- O menu lateral não deve mostrar qualquer opção que o usuário externo não deva acessar.

### Tela

[Acesse aqui o Protótipo no Figma](https://www.figma.com/proto/5H0LzFn68c7enYpmkWexUF/Prot%C3%B3tipo-Schedula---US06---Chamados-para-usu%C3%A1rio-externo?type=design&node-id=30-2&scaling=contain&page-id=0%3A1&starting-point-node-id=30%3A2) (falta validação)

- A issue deve ser pontuada;
- A issue deve ser delegada a alguém;
- A issue deve ter labels;

**Comment by gabrielbpn** [comment]
![image](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/assets/58351486/abf8e206-4657-4d63-b2a3-4989409eed9d)

**Comment by guilhermemoraisr** [comment]
Protótipo atualizado após reunião da quinta-feira com os clientes.

Mudanças realizadas:
- alteração do escopo da página de "chamados" para "agendamentos", após clarificação pelos POs;
- atualização e ilustração dos status desejados a serem visualizados na página: "não resolvido", "pendente", "urgente" e "em andamento" - os padrões de cores e posicionamento do status foram mantidos conforme existe atualmente no Schedula, que acreditamos que já tenha passado por validação do semestre anterior, e preferimos não alterar.

**Comment by guilhermepupak** [comment]
Critérios de aceitação:

- Obs. Acredito que basta apenas um Botão (MENU) chamado **AGENDAMENTOS**, assim que o usuário clicar, irá para a Tela onde ele poderia consultar os agendamentos aberto, ou registrar um atendimento (que após homologação tornará um agendamento)

Qualquer usuário pode ver o botão de "AGENDAMENTOS" na tela de login;
Qualquer usuário pode acessar a página de AGENDAMENTOS;
A página de agendamentos deve listar todos os agendamentos abertos;
A página de agendamentos não deve listar qualquer agendamento que não esteja aberto (ex: homologação, fechado ou resolvido);
Os dados do agendamento devem ser exatamente os registrados no banco;
O botão de novo agendamento deve levar à página de criação de agendamentos por usuário externo;
O identificador de usuário deve ser mostrado como usuário externo e, quando clicado, deve voltar à pagina de login;
O menu lateral não deve mostrar qualquer opção que o usuário externo não deva acessar.



Exemplos de ícones para menu de Agendamentos:

![image](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/assets/109108065/12479967-3798-42f9-a61b-04f847ed0172)

![image](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/assets/109108065/d7395493-d98b-4f38-96ac-438cc14f1c5b)
![image](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/assets/109108065/f4096b38-11aa-4d4a-8dc7-844aef3dc219)
![image](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/assets/109108065/7f258756-276a-4215-b6b7-a2357d9f5707)

**Comment by juliassmendonca** [comment]
Atualizamos o protótipo referente a esta US conforme o pedido!

**Comment by guilhermemoraisr** [comment]
## 📑 Test Plan

1. Verificar se na página de login há um botão chamado "Agendamentos". E se ao clicar nele ou no ícone acima dele, você é direcionado à página de agendamentos abertos.

![image](https://github.com/fga-eps-mds/2023-1-schedula-front/assets/48729770/c739046c-896e-4f3c-b287-1aae14cb6792)

2. Verificar se a página de agendamentos abertos se apresenta conforme a imagem abaixo, sendo listados todos os agendamentos abertos com status: NÃO RESOLVIDO, EM ANDAMENTO, PENDENTE e URGENTE. Não é permitido que apareça algum agendamento com status "RESOLVIDO". o nome do usuário na parte inferior deve estar registrado como "usuário externo". Na barra lateral de acessos, deve haver apenas as opções que o usuário externo pode ver, ou seja, apenas a página de Agendamentos Abertos. Deve haver o botão de "Novo Agendamento", que não deve ter ação, pois está aguardando o prazo de finalização da US que cria esta página.

![image](https://github.com/fga-eps-mds/2023-1-schedula-front/assets/48729770/2342c882-f797-4021-b502-367b937d0538)
