### ISSUE TITLE
[US07] - Abertura de Agendamento por usuário externo

### ISSUE THREAD

**Issue by AlvaroLeles** [fga-eps-mds/2023-1-Schedula-Doc#31]
### Tarefas:

- [x] Criar um botão para redirecionar para os agendamentos não finalizados;
- [x] Criar um botão para redirecionar para a página de login;
- [x] Criar tela para criação de um agendamento;

### Critérios de aceitação:

- Garantir que o e-mail seja o institucional;
- Conseguir pegar a Cidade do banco de dados ;
- Conseguir pegar o Posto de Trabalho do banco de dados;
- Conseguir pegar a Categoria de Problema do banco de dados ;
- Conseguir pegar o Tipo de Problema do banco de dados;
- Após a criação do chamado redirecionar para a página de listagem de agendamentos;
- (Solicitação do cliente) Permitir que o usuário administrador da aplicação escolha quais Categorias e Tipos de Problemas, serão liberados para a abertura de agendamentos por usuário externo;
- (Solicitação do cliente) O usuário externo deverá obrigatoriamente mencionar um telefone celular;

### [Tela do Protótipo](https://www.figma.com/file/Lltx2g5DDVIYgOseDuEBCh/%5BUS07%5D---Abertura-de-chamados-por-usu%C3%A1rio-externo-team-library?type=design&node-id=0%3A1&t=g8QBCOF8JNhYsZWB-1)

- A issue deve ser pontuada;
- A issue deve ser delegada a alguém;
- A issue deve ter labels;

## 📑 Test Plan
0- OBS: É importante ter o banco de cidade, posto de trabalho, categoria e tipo de problema cadastrado
1- Na tela de Login clique no botão de agendamentos
![image](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/assets/70165759/af94f5fc-70dd-4df5-a767-715a473a6a52)
2- No menu clique em Registrar agendamento, para acessar a seguinte página:
![image](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/assets/70165759/b60f1f4a-9a8a-4f62-b226-384e97f307b5)
3- Preencha os campos, e verifique se os campos obrigatórios(todos os campos) estão como obrigatórios
4- Verifique se o formato do e-mail está correto
5- Com tudo preenchido, clique em registrar agendamento
![image](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/assets/70165759/da6d2d13-a49a-4aab-b285-42a9d76f877d)
6- Pronto!!
![image](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/assets/70165759/a107bb24-a3eb-4a15-bdfa-cb5a189c629c)

**Comment by guilhermepupak** [comment]
Critérios de aceitação:

- Garantir que o e-mail seja o institucional;
- Conseguir pegar a Cidade do banco de dados ;
- Conseguir pegar o Posto de Trabalho do banco de dados;
- Conseguir pegar a Categoria de Problema do banco de dados ;
- Conseguir pegar o Tipo de Problema do banco de dados;
- Permitir que o usuário administrador da aplicação escolha quais **Categorias** e **Tipos de Problemas**, serão liberados para a abertura de chamados por usuário externo;
- O usuário externo deverá obrigatoriamente mencionar um telefone celular;
- Após a criação do chamado redirecionar para a página de listagem de chamados;

**Comment by gabrielbpn** [comment]
![image](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/assets/58351486/11036e80-0447-4a47-839e-f2723981cb13)

**Comment by italofernandes13** [comment]
Alterações:
1. Nome da historia de usuário: 
1.1. [US07] - Abertura de **Chamando** por usuário externo (Antigo)
1.2. [US07] - Abertura de **Agendamento** por usuário externo (Novo)
2. Descrição:
2.1. Eu como usuário externo desejo criar um **chamado para expor meu problema para os usuários internos**. (Antigo)
2.2. Eu como usuário externo desejo criar um **agendamento para solucionar um problema**. (Novo)
3. Tarefas:
3.1. Criar um botão para redirecionar para os **chamados abertos**; (Antigo)
3.2. Criar um botão para redirecionar para os **agendamento não finalizados**; (Novo)
3.3. Criar um botão na página de login para criar um **chamado**; (Antigo)
3.4. Criar um botão na página de login para criar um **agendamento**; (Novo)
3.5. Criar tela para criação de um **chamado**; (Antigo)
3.6. Criar tela para criação de um **agendamento**; (Novo)
4. Critério de aceitalção
4.1. Após a criação do **chamado** redirecionar para a página de listagem de **chamados**; (Antigo)
4.2. Após a criação do **agendamento** redirecionar para a página de listagem de **agendamentos**; (Novo)
4.3. (Solicitação do cliente) Permitir que o usuário administrador da aplicação escolha quais Categorias e Tipos de Problemas, serão liberados para a abertura de **chamados** por usuário externo; (Antigo)
4.4. (Solicitação do cliente) Permitir que o usuário administrador da aplicação escolha quais Categorias e Tipos de Problemas, serão liberados para a abertura de **agendamentos** por usuário externo; (Novo)
