### ISSUE TITLE
[US08] - Listar e homologar atendimentos abertos por usuário externo na área de homologação de atendimentos

### ISSUE THREAD

**Issue by AlvaroLeles** [fga-eps-mds/2023-1-Schedula-Doc#33]
### Tarefas:

- [x] Criar botão no menu lateral da aplicação;
- [x] Criar card de atendimentos após usuário externo abrir o atendimentos;
- [x] Listar os atendimentos abertos pelos usuários externos; 
- [x] Criar botões de aprovação e reprovação nos cards dos atendimentos abertos pelos usuários externos;
- [x] Criar botão de edição nos cards dos atendimentos abertos pelos usuários externos para que o administrador possa alterar alguma informação do atendimento.
- [ ] Criar pop-up para que o administrador tenha a opção de adicionar um horário de agendamento e um horário de alerta referente ao agendamento a ser feito. Essa adição de horários é opcional ao administrador.
- [ ] Criar pop-up para que o administrador justifique a reprovação do atendimento;
- [ ] Notificar usuário externo do resultado da homologação via email;

### Critérios de aceitação:

- O mesmo atendimento esperando por homologação não pode aparecer duas vezes na lista;
- O administrador deverá conseguir ver o botão de homologação no menu lateral;
- Um usuário que não seja administrador não deverá conseguir ver a tela de homologação;
- O administrador deverá conseguir acessar a tela de homologação;
- O administrador deverá conseguir visualizar a tela de atendimentos abertos por usuários externos;
- Um atendimento que já foi aprovado ou reprovado não deve aparecer na listagem;
- O administrador deverá conseguir aprovar um atendimento aberto;
- O administrador deverá conseguir reprovar um atendimento aberto;
- O administrador deverá justificar uma reprovação de um atendimento;
- O usuário externo deverá ser notificado via email sobre o resultado da homologação;
- O administrador deverá conseguir editar alguma informação do atendimento aberto se achar necessário.
- O administrador deverá conseguir registrar um horário de agendamento e um horário de alerta após aprovar um atendimento, se assim achar necessário.
- CI estar passando;
- Respeitar todas as orientações acima.

**Comment by gabrielbpn** [comment]
![image](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/assets/58351486/26e7159e-a90e-477c-8927-55e1c3771c84)

**Comment by gabrielbpn** [comment]
- Alterações depois do alinhamento feito em reunião com os POs:

1. Ajuste no título da história de usuário para alterar "chamados" para "atendimentos".
2. Ajuste nas tarefas e nos critérios de aceitação para alterar "chamados" para "atendimentos".
3. Ajuste no protótipo para adicionar o "Posto de Trabalho" nas informações do card de atendimento.

**Comment by guilhermepupak** [comment]
Critérios de aceitação:

- O mesmo atendimento esperando por homologação não pode aparecer duas vezes na lista;
- O administrador deverá conseguir ver o botão de homologação no menu lateral;
- Um usuário que não seja administrador não deverá conseguir ver a tela de homologação;
- O administrador deverá conseguir acessar a tela de homologação;
- O administrador deverá conseguir visualizar a tela de atendimentos abertos por usuários externos;
- Um atendimento que já foi aprovado ou reprovado não deve aparecer na listagem;
- O administrador deverá conseguir aprovar um atendimento aberto;
- O administrador deverá conseguir reprovar um atendimento aberto, nesse caso deverá justificar o motivo da reprovação;
- O administrador deverá justificar uma reprovação de um atendimento;
- O usuário externo deverá ser notificado via email sobre o resultado da homologação;
- O administrador deverá conseguir editar alguma informação do atendimento aberto se achar necessário.
- O administrador deverá conseguir registrar um horário de agendamento e um horário de alerta após aprovar um atendimento, se assim achar necessário.

Eu gostaria que fosse realocada algumas informações para a tela dos atendimentos, na Homologação, como Posto de Trabalho, Local, Solicitante, Celular do Solicitante, Data e Hora, e abaixo o campo Descrição de forma completa, bem como ícones de aprovação (verde), edição (amarelo) e reprovação (vermelho), conforme a imagem abaixo:

![image](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/assets/109108065/00cb8da8-868a-4952-bcab-4de69999e8d3)


Inserir campos de DATA e ALERTA:
![image](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/assets/109108065/368fc7b9-226d-4a02-83dc-0414acf49227)

**Comment by gabrielsarcan** [comment]
@guilhermepupak obrigado pela validação. Eu e a equipe estamos cientes da sua orientação e vamos aplica-las.

**Comment by gabrielbpn** [comment]
## 📑 Roteiro de testes

### Como Admin
1. Ao acessar a aplicação como administrador, poderá ver o botão de "Homologação" na barra lateral esquerda e acessá-la clicando no botão.

2. Ao entrar, poderá ver os cards dos agendamentos abertos pelos usuários externos (caso não haja nenhum card, será preciso criar um agendamento entrando como usuário externo - [US07](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/issues/31)
![image](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/assets/58351486/be2bc282-aaed-45d7-8b95-6fd6cd7af5a8)

3. Para testar as funcionalidades dos botões, basta clicar neles. O botão verde representa a "aprovação da homologação", o amarelo é a "edição" da homologação e o vermelho é a "reprovação".

![image](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/assets/58351486/4a2b641b-7673-4258-a551-7c9439fc39aa)

4. Dito isso, você poderá alterar as informações do usuário ao clicar em "editar". Como o "telefone" é algum fixo do posto de trabalho, não há a opção de editá-lo.

![image](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/assets/58351486/f33d4a24-239b-4a58-a81c-562f3b8c90ea)

5. Ao clicar em "aprovar", aparecerá a opção de adicionar uma data de agendamento e um alerta quando ele virar um agendamento aprovado.

![image](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/assets/58351486/1538f115-2898-47cf-8318-12c177e0dd06)

6. Ao clicar em reprovar, você poderá adicionar uma justificativa ao qual está reprovando o agendamento.

![image](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/assets/58351486/f1101922-86dd-4fb6-baf6-c55e40fa201a)

7. Após uma aprovação, você poderá ver os agendamentos aprovados na lista de "agendamentos", assim como os atendimentos que foram agendados.

![image](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/assets/58351486/81b27915-c843-4460-8b03-1b92b50ae2a3)

Observações:

- A função de alertas não está funcional. Ao clicar em adicionar alertas na edição do agendamento, você encontrará um erro que será preciso atualizar a página. Tal alerta também não está passando preenchido para a parte de agendamentos. Já estamos trabalhando nisso.

- Como conversado e discutido em reunião, o envio de e-mail contempla atualmente o serviço do GMAIL. Para contemplar os e-mails da @policiacivil.go.gov.br, será preciso ajustar de acordo com suas necessidades um arquivo como o .env para que seja adicionado o usuário que enviará o e-mail, assim como sua senha de aplicativo e serviços necessários. Tal discussão já foi alinhada em reunião, sendo possível ser discutida posteriormente.
