### ISSUE TITLE
[US10] - Menu de alertas

### ISSUE THREAD

**Issue by AlvaroLeles** [fga-eps-mds/2023-1-Schedula-Doc#41]
### Descrição:

Eu como usuário terei um MENU com as listagens das tarefas repassadas pelo administrador, para que possa que possa interagir com as mesmas.

### Tarefas:

- [x] Possuir botão de notificações ;
- [x] Mostrar quantas notificações não foram visualizadas ;
- [x] Criar a rota para a página de notificações ;
- [x] Possuir botões para "Marcar como resolvido" e "Pendencia" ;
- [x] Campo de busca por notificação;
- [x] Pop-up que aloque campo para descrição de pendencia;
- [x] Campo para descrição de "motivo para pendencia opcional" da notificação;
- [x]  Comunicação das funções criadas com o banco de dados ;
- [x]  Testes para os códigos ;

### Critérios de aceitação:

- Quando os usuários logarem na aplicação, deverá ter um ícone (um SINO), onde serão acionados os ALERTAS, informando-o que recebeu uma tarefa do seu Chefe;
- O usuário deverá conseguir acessar o menu de notificações, para marcar o alerta como PENDENTE ou RESOLVIDO;
- Se o usuário marcar o alerta como PENDENTE, poderá relatar o motivo da pendência;
- Se o usuário marcar o alerta como RESOLVIDO, o alerta deverá sumir automaticamente para o subordinado;
- Quando o usuário visualizar o alerta de tarefas, a aplicação deverá marcar como lida automaticamente. Assim, o Chefe poderá verificar que o usuário já leu a mensagem do alerta;
- CI estar passando ;
- Respeitar todas as orientações acima.

### Observações 

Teremos como INTERAÇÃO, ações do tipo "marcar como resolvida" e " marcar pendência", não sendo relacionadas a conversas do tipo "Chat".
 
### Protótipo de tela no FIGMA para menu em [PÁGINA](https://www.figma.com/proto/RnS7HfhodnrXFTKxmpLjib/Protótipo-Notificações-em-página?type=design&node-id=76-2&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=76%3A2)

**Comment by guilhermepupak** [comment]
Mudar a História de usuário para **Menu de Alerta de Tarefas**

Critérios de aceitação:
- Eu como administrador (Chefe do Departamento) irei criar os Alertas de Tarefas, e direcioná-los para determinados subordinados (servidores), usuários internos da aplicação;
- Eu como administrador terei um MENU com as listagens das tarefas repassadas aos subordinados;
- Os alertas poderão ter 3 status: NÃO RESOLVIDO; PENDENTE e RESOLVIDO;
- Eu como administrador poderei filtrar as tarefas RESOLVIDAS, PENDENTES ou NÃO RESOLVIDAS;
- Quando os usuários logarem na aplicação, deverá ter um ícone (um SINO), onde serão acionados os ALETAS, informando-o que recebeu uma tarefa do seu Chefe. Exemplo ilustrativo do ícone;
- ![image.png](https://images.zenhubusercontent.com/62cc81162c32b7cedef5de42/81372e10-94ff-446b-8773-830c85d40536)
- O usuário deverá conseguir acessar o menu de notificações, para marcar o alerta como PENDENTE ou RESOLVIDO;
- Se o usuário marcar o alerta como PENDENTE, poderá relatar o motivo da pendência;
- Se o usuário marcar o alerta como RESOLVIDO, o alerta deverá sumir automaticamente para o subordinado;
- Quando o usuário visualizar o alerta de tarefas, a aplicação deverá marcar como lida automaticamente. Assim, o Chefe poderá verificar que o usuário já leu a mensagem do alerta;

**Comment by gabrielbpn** [comment]
![image](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/assets/58351486/568840a1-c491-4a99-8d84-f51e34166a0d)

**Comment by IanFPFerreira** [comment]
## 📑 Roteiro de testes

### Como BASIC
1. Ao acessar a aplicação, verificar se o contador de notificações aparece corretamente
![image](https://github.com/fga-eps-mds/2023-1-schedula-front/assets/46847658/a7a714a1-cedf-4b96-928c-5eb70a603a5c)
OBS.: Ao acessar a tela de notificações, elas mudam automaticamente para 'visualizada'
2. Adicionar pendência, e verificar que o botão muda de cor
![image](https://github.com/fga-eps-mds/2023-1-schedula-front/assets/46847658/1561a87e-d701-416d-8e08-1302a1db7830)
3. Marcar notificação como resolvida e visualizar se a notificação desaparece do tela
