### ISSUE TITLE
[US11] - Usuário admin notificar usuário

### ISSUE THREAD

**Issue by AlvaroLeles** [fga-eps-mds/2023-1-Schedula-Doc#42]
### Descrição:

Eu como usuário administrador gostaria de alertar outro usuário com alguma mensagem para que ele seja informado de algo.

### Tarefas:

- [x] Acessar funcionalidade de notificar;
- [x] Inserir informações (email e conteúdo);
- [x] Enviar a notificação;
- [x] Acompanhar o status do alerta
- [x] Verificar quais as pendências
- [x] Remover um alerta
- [x] Filtrar alerta pelo status

### Critérios de aceitação:

- Usuário admin conseguirá ver o botão de notificar;
- O usuário admin deve conseguir inserir o texto desejados;
- O texto terá um limite de 500 caracteres;
- O email do destinatário será listado a partir da digitação;
- O usuário admin consegue verificar se o email do destinatário é válido;
- Usuário admin poderá enviar a notificação;
- Usuário admin acompanhará status dos alertas enviados

### Observações (caso não tenha, delete essa parte)

Pergunta: 
Todos os níveis de usuários usarão esta funcionalidade? Somente admin possuirá a funcionalidade de enviar alertas
A notificação será feita para mais de um usuário? Não, será destinada apenas a um usuário

### Tela (caso não tenha, delete essa parte)

Usamos duas estratégias:
- Uma usando [páginas](https://www.figma.com/proto/x66YDo7cOnl99FlDy1Y0vq/US11-Usu%C3%A1rio-notificar-usu%C3%A1rio?type=design&node-id=0-1&scaling=min-zoom&starting-point-node-id=1%3A36&show-proto-sidebar=1)

**Comment by guilhermepupak** [comment]
Critérios de aceitação:

- Apenas usuário com perfil de administrador poderá enviar Alerta de Tarefas (notificações) para outros usuários;
- O texto terá um limite de 500 caracteres;   

Obs.: os demais critérios foram mencionados na história US10

**Comment by gabrielbpn** [comment]
![image](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/assets/58351486/a9063f7a-0634-429d-a008-04a5c7526f3a)

**Comment by IanFPFerreira** [comment]
## 📑 Test Plan

### Como ADMIN

1. Acessar a tela de notificações
2. Criar notificações
![image](https://github.com/fga-eps-mds/2023-1-schedula-front/assets/46847658/b9993749-488e-4a0e-8801-b9d794d90e0f)
OBS.: Verificar se na seleção de destinatário aparece apenas usuários do tipo BASIC
3. Visualizar as notificações criadas
![image](https://github.com/fga-eps-mds/2023-1-schedula-front/assets/46847658/a66e5259-bd94-44d1-a90b-850e427d6d54)
4. Verificar que os cards sinalizam que a notificação foi visualizada, quando o BASIC acessa a tela de notificações
![image](https://github.com/fga-eps-mds/2023-1-schedula-front/assets/46847658/5680a6c1-34b7-4395-b2cf-f0a51992f662)
5. Verificar que os status mudam dependendo da mudança feita pelo BASIC
![image](https://github.com/fga-eps-mds/2023-1-schedula-front/assets/46847658/7ae01ac2-c5f6-4402-b9e8-a147572a22bc) 
![image](https://github.com/fga-eps-mds/2023-1-schedula-front/assets/46847658/5af8d158-fcd7-49b1-aca3-3a2b8e5e8e0b)
6. Verificar que se o BASIC escreve um motivo da pendência, esse motivo aparece no card
![image](https://github.com/fga-eps-mds/2023-1-schedula-front/assets/46847658/ce6528b0-27b8-4b8a-ad9e-fe82254e6873)
8. Testar deleção da notificação
