### ISSUE TITLE
[US13] - Exportar relatórios

### ISSUE THREAD

**Issue by AlvaroLeles** [fga-eps-mds/2023-1-Schedula-Doc#45]
### Tarefas:

- [x] Exportar arquivo pdf
- [x] Quantidade de atendimentos
- [x] Quantidade de atendimentos e agendamentos abertos (INTERNO/EXTERNO)
- [x] Quantidade de agendamentos
- [x] Quantidade de atendimentos agrupada por categoria e tipo de problema
- [x] Quantidade de agendamento agrupada por categoria e tipo de problema
- [x] Gráfico com a quantidade de agendamentos agrupado por status

### Critérios de aceitação:

- Relatório será gerado por meio de um filtro
- Tem que ter cabeçalho e rodapé da polícia
- Deve ser gerado em PDF
- As cores dos status deverão seguir a ordem:
    - NÃO RESOLVIDO = Laranja
    - EM ANDAMENTO = Azul
    - PENDENTE = Amarelo
    - URGENTE = Vermelho
    - RESOLVIDO = Verde

**Comment by gabrielbpn** [comment]
![image](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/assets/58351486/860eedeb-6f65-447f-8826-7ede5d866242)

**Comment by IanFPFerreira** [comment]
## Roteiro de testes
1. A função de exportar relatórios e acessada através da tela de Atendimentos
![image](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/assets/46847658/6cd1bf4b-cd1f-415c-b23a-48142652cdc4)
2. Para gerar o relatório deve ser selecionado o filtro de período (Inicial e Final)
![image](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/assets/46847658/32244e1e-3086-4a32-9a5d-a3832b1c2138)
3. Quando selecionado um período que não contém nenhum atendimento, é gerado um relatório no formato:

|Atendimentos|Agendamentos|
|--|--|
|![image](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/assets/46847658/8e19a65a-7d8b-40bf-b8bc-1b21eb15fce8)|![image](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/assets/46847658/a7077b2c-cbe5-460e-88b5-1f27eb8b2824)|

4. Quando selecionado um período que contém um atendimento, é gerado um relatório no formato:

|Atendimentos|Agendamentos|
|:--:|:--:|
| ![image](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/assets/46847658/61cb6494-907c-42c2-90dd-20dfed3b2ea9) | ![image](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/assets/46847658/97d6e34e-2f88-471e-b5b0-7be58e13f63a) |
