### ISSUE TITLE
Prototipar tela de acesso de tutoriais

### ISSUE THREAD

**Issue by AlvaroLeles** [fga-eps-mds/2023-1-Schedula-Doc#54]

**Comment by gabrielbpn** [comment]
![image](https://user-images.githubusercontent.com/58351486/236078121-9247d7b7-c668-49e2-a2a7-c29fdc5f4101.png)

**Comment by guilhermemoraisr** [comment]
https://www.figma.com/proto/Zn3jP0CN3ANk2Aruz3Vegg/Acessar-tutoriais?type=design&node-id=9-10&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=9%3A10
