### ISSUE TITLE
Resolver problema de edição e exclusão de usuário

### ISSUE THREAD

**Issue by AlvaroLeles** [fga-eps-mds/2023-1-Schedula-Doc#55]
Edição de usuário abre um formulário vazio, deleção dispara um erro

**Comment by gabrielbpn** [comment]
![image](https://user-images.githubusercontent.com/58351486/236077870-f3caab4d-eedd-4b06-89a1-83b7c4eed24e.png)

**Comment by AlvaroLeles** [comment]
Exclusão lógica: MARCAR o usuário como excluído, e manter o que foi criado por ele no sistema
