### ISSUE TITLE
Criação da frase da história de US05, critérios de aceitação e criar protótipo (gerenciamento de tutoriais)

### ISSUE THREAD

**Issue by AlvaroLeles** [fga-eps-mds/2023-1-Schedula-Doc#58]
### Descrição:
Criar a história de usuário 05 com suas tarefas para validar nas reuniões, e modelar um protótipo de alta fidelidade para a história.

### Tarefas:

- [x] Criar a história de usuário 05 - Gerenciamento de tutoriais #28;
- [x] Criar um protótipo de alta fidelidade para o gerenciamento de tutoriais;

**Comment by gabrielavelino** [comment]
Dia 05/05 foi criado a US05 e adicionada na issue PAI.

**Comment by gabrielavelino** [comment]
Protótipo das telas de gerenciamento de tutoriais:

<https://www.figma.com/file/e1d9VEVrL7jw8P6xlmuXHZ/Prot%C3%B3tipo-Schedula---US05---Gerenciamento-de-Tutoriais?node-id=5%3A367&t=BfrAsCMZbZoce8ue-1>
