### ISSUE TITLE
Incluir CPF no cadastro de usuário

### ISSUE THREAD

**Issue by AlvaroLeles** [fga-eps-mds/2023-1-Schedula-Doc#67]

**Comment by gabrielbpn** [comment]
![image](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/assets/58351486/0d9d75d3-540b-4cc6-bbb7-efffbd169cc5)

**Comment by italovinicius18** [comment]
![image.png](https://images.zenhubusercontent.com/61f169759f9e93fed76ab027/25e00b3f-9b73-4656-8696-d7462bee11b2)
![image.png](https://images.zenhubusercontent.com/61f169759f9e93fed76ab027/3679b346-0918-4fea-8af6-7e0b098ab199)
