### ISSUE TITLE
Alterar tela de gerenciamento de postos de trabalho conforme solicitações

### ISSUE THREAD

**Issue by AlvaroLeles** [fga-eps-mds/2023-1-Schedula-Doc#70]

**Comment by AlvaroLeles** [comment]
![Cadastro_de_Posto_de_Trabalho_Schedula.png](https://images.zenhubusercontent.com/61f16ac79f9e93d37b6ab02a/019f4fcb-7fdc-4a2f-932f-10cc4fa1854b)

**Comment by AlvaroLeles** [comment]
"Todos os campos seriam desabilitados. Como podemos ver na planilha da imagem, em caso de VPN, não é necessário informar Gateway e nem as Faixas."

**Comment by gabrielsarcan** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Kanban---Schedula-2023-1-64371d3cd8b7ae0015a4db77/issues/fga-eps-mds/2023-1-Schedula-Doc/70?planning-poker) with Zenhub @italovinicius18 @fillipeb50
