### ISSUE TITLE
Campo de descrição em agendamentos

### ISSUE THREAD

**Issue by gabrielbpn** [fga-eps-mds/2023-1-Schedula-Doc#98]
## Descrição da Issue
O campo de descrição na tela de agendamentos não está com a responsividade correta: quando têm muitos caracteres, ele ultrapassa o card e não fica no enquadramento correto.

## Tasks:
- [x] Arrumar esse bug.

**Comment by AlvaroLeles** [comment]
Acredito que o melhor caminho a seguir é a limitação de caracteres, até por que foi mencionado que o texto da descrição tem que aparecer inteiro em situações onde o espaço é menor

**Comment by gabrielbpn** [comment]
Acho melhor validar isso com o PO, @AlvaroLeles. Não sei se ele vai curtir muito isso de limitar (e se limitar, imagino que seja pra muitos caracteres).

**Comment by gabrielavelino** [comment]
Foi definido com o PO que o campo ao clicar no card será expandido contendo o campo de descrição completo.
